// generator.c - Shell file generation
#include "shtick.h"
#include <sys/stat.h>

static void generate_bash_function(FILE *fp, const Function *func) {
    fprintf(fp, "%s() {\n", func->name);
    
    // Output function body with proper indentation
    const char *body = func->body;
    while (*body) {
        fprintf(fp, "    ");
        while (*body && *body != '\n') {
            fputc(*body, fp);
            body++;
        }
        fputc('\n', fp);
        if (*body == '\n') body++;
    }
    
    fprintf(fp, "}\n");
}

static void generate_fish_function(FILE *fp, const Function *func) {
    fprintf(fp, "function %s\n", func->name);
    
    // Output function body with proper indentation
    const char *body = func->body;
    while (*body) {
        fprintf(fp, "    ");
        while (*body && *body != '\n') {
            fputc(*body, fp);
            body++;
        }
        fputc('\n', fp);
        if (*body == '\n') body++;
    }
    
    fprintf(fp, "end\n");
}

int generate_shell_file(const char *shell_type) {
    char output_dir[MAX_PATH];
    char output_path[MAX_PATH];
    const char *home = getenv("HOME");
    if (!home) home = ".";
    
    // Validate shell_type length to prevent overflow
    if (strlen(shell_type) > 32) {
        fprintf(stderr, "Error: Shell type name too long\n");
        return -1;
    }
    
    for (int i = 0; i < g_config.group_count; i++) {
        Group *group = &g_config.groups[i];
        
        if (group->alias_count == 0 && group->env_var_count == 0 && group->function_count == 0) continue;
        
        // Create output directory with bounds checking
        int dir_len = snprintf(output_dir, sizeof(output_dir), "%s/.config/shtick/%s", home, group->name);
        if (dir_len >= (int)sizeof(output_dir)) {
            fprintf(stderr, "Error: Path too long for group %s\n", group->name);
            continue;
        }
        ensure_directory(output_dir);
        
        // Create output file with bounds checking
        int path_len = snprintf(output_path, sizeof(output_path), "%s/all.%s", output_dir, shell_type);
        if (path_len >= (int)sizeof(output_path)) {
            fprintf(stderr, "Error: Output path too long for group %s\n", group->name);
            continue;
        }
        
        FILE *fp = fopen(output_path, "w");
        if (!fp) {
            fprintf(stderr, "Error: Cannot create %s\n", output_path);
            continue;
        }
        
        fprintf(fp, "# Shtick configuration for %s - %s\n", group->name, shell_type);
        fprintf(fp, "# Generated by shtick - DO NOT EDIT\n");
        fprintf(fp, "# Modify using: shtick add/remove commands\n\n");
        
        // Generate aliases
        if (group->alias_count > 0) {
            fprintf(fp, "# Aliases (%d)\n", group->alias_count);
            for (int j = 0; j < group->alias_count; j++) {
                Item *alias = &group->aliases[j];
                char escaped_value[MAX_VALUE * 2];
                
                if (strcmp(shell_type, "bash") == 0 || strcmp(shell_type, "zsh") == 0) {
                    escape_bash_value(alias->value, escaped_value, sizeof(escaped_value));
                    fprintf(fp, "alias %s=%s\n", alias->key, escaped_value);
                } else if (strcmp(shell_type, "fish") == 0) {
                    escape_fish_value(alias->value, escaped_value, sizeof(escaped_value));
                    fprintf(fp, "alias %s %s\n", alias->key, escaped_value);
                }
            }
            fprintf(fp, "\n");
        }
        
        // Generate environment variables
        if (group->env_var_count > 0) {
            fprintf(fp, "# Environment Variables (%d)\n", group->env_var_count);
            for (int j = 0; j < group->env_var_count; j++) {
                Item *env = &group->env_vars[j];
                char escaped_value[MAX_VALUE * 2];
                
                if (strcmp(shell_type, "bash") == 0 || strcmp(shell_type, "zsh") == 0) {
                    escape_bash_value(env->value, escaped_value, sizeof(escaped_value));
                    fprintf(fp, "export %s=%s\n", env->key, escaped_value);
                } else if (strcmp(shell_type, "fish") == 0) {
                    escape_fish_value(env->value, escaped_value, sizeof(escaped_value));
                    fprintf(fp, "set -x %s %s\n", env->key, escaped_value);
                }
            }
            fprintf(fp, "\n");
        }
        
        // Generate functions
        if (group->function_count > 0) {
            fprintf(fp, "# Functions (%d)\n", group->function_count);
            for (int j = 0; j < group->function_count; j++) {
                Function *func = &group->functions[j];
                
                if (strcmp(shell_type, "bash") == 0 || strcmp(shell_type, "zsh") == 0) {
                    generate_bash_function(fp, func);
                } else if (strcmp(shell_type, "fish") == 0) {
                    generate_fish_function(fp, func);
                }
                
                if (j < group->function_count - 1) {
                    fprintf(fp, "\n");
                }
            }
        }
        
        fclose(fp);
    }
    
    // Generate loader file with bounds checking
    int loader_len = snprintf(output_path, sizeof(output_path), "%s/.config/shtick/load_active.%s", home, shell_type);
    if (loader_len >= (int)sizeof(output_path)) {
        fprintf(stderr, "Error: Loader path too long\n");
        return -1;
    }
    
    FILE *fp = fopen(output_path, "w");
    if (!fp) {
        fprintf(stderr, "Error: Cannot create loader file\n");
        return -1;
    }
    
    fprintf(fp, "# Shtick dynamic loader for %s\n", shell_type);
    fprintf(fp, "# This file is auto-generated - do not edit\n\n");
    
    // Check for shell type and add appropriate comments
    if (strcmp(shell_type, "bash") == 0 || strcmp(shell_type, "zsh") == 0) {
        fprintf(fp, "# Source this file in your ~/.bashrc or ~/.zshrc:\n");
        fprintf(fp, "#   source ~/.config/shtick/load_active.%s\n\n", shell_type);
    } else if (strcmp(shell_type, "fish") == 0) {
        fprintf(fp, "# Source this file in your ~/.config/fish/config.fish:\n");
        fprintf(fp, "#   source ~/.config/shtick/load_active.fish\n\n");
    }
    
    // Load persistent group
    fprintf(fp, "# Load persistent configuration (always active)\n");
    if (strcmp(shell_type, "fish") == 0) {
        fprintf(fp, "if test -f \"$HOME/.config/shtick/persistent/all.fish\"\n");
        fprintf(fp, "    source \"$HOME/.config/shtick/persistent/all.fish\"\n");
        fprintf(fp, "end\n\n");
    } else {
        fprintf(fp, "[ -f \"$HOME/.config/shtick/persistent/all.%s\" ] && source \"$HOME/.config/shtick/persistent/all.%s\"\n\n", 
                shell_type, shell_type);
    }
    
    // Load active groups
    if (g_config.active_group_count > 0) {
        fprintf(fp, "# Load active groups\n");
        for (int i = 0; i < g_config.active_group_count; i++) {
            fprintf(fp, "# Group: %s\n", g_config.active_groups[i]);
            if (strcmp(shell_type, "fish") == 0) {
                fprintf(fp, "if test -f \"$HOME/.config/shtick/%s/all.fish\"\n", g_config.active_groups[i]);
                fprintf(fp, "    source \"$HOME/.config/shtick/%s/all.fish\"\n", g_config.active_groups[i]);
                fprintf(fp, "end\n");
            } else {
                fprintf(fp, "[ -f \"$HOME/.config/shtick/%s/all.%s\" ] && source \"$HOME/.config/shtick/%s/all.%s\"\n",
                        g_config.active_groups[i], shell_type, g_config.active_groups[i], shell_type);
            }
        }
    } else {
        fprintf(fp, "# No active groups\n");
    }
    
    fclose(fp);
    return 0;
}